### ISSUE TITLE
Tests fail when run with JDK11

### ISSUE THREAD

**Issue by richardstartin** [DiegoEliasCosta/spotjmhbugs#1]
Seems unable to read bytecode compiled by JDK11.
```
testUnsinkedvariableWithDCE(de.heidelberg.pvs.diego.detectors.UnsinkedVariableBenchmarkDetectorTest)  Time elapsed: 0.063 sec  <<< ERROR!
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:160)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:143)
        at edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
        at edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
        at edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
        at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
        at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
        at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
        at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
        at edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:677)
        at edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:970)
        at edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:876)
        at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:222)
        at edu.umd.cs.findbugs.test.AnalysisRunner.run(AnalysisRunner.java:118)
        at edu.umd.cs.findbugs.test.SpotBugsRule.performAnalysis(SpotBugsRule.java:118)
        at de.heidelberg.pvs.diego.detectors.UnsinkedVariableBenchmarkDetectorTest.testUnsinkedvariableWithDCE(UnsinkedVariableBenchmarkDetectorTest.java:26)
```

**Comment by mjw99** [comment]
Seeing something similar with 4cc0e9079fd31 ; Ubuntu 18.04.2, openjdk version "11.0.3"

**Comment by DiegoEliasCosta** [comment]
Thanks for reporting guys. Let me take a look at this issue over the weekend.

**Comment by DiegoEliasCosta** [comment]
The Spotbugs version used by SpotJMHBugs (3.1.0) did not support [Java 10](https://github.com/spotbugs/spotbugs-gradle-plugin/issues/21), [11](https://github.com/spotbugs/spotbugs/issues/711) and [12](https://github.com/spotbugs/spotbugs/issues/788).

Updated to the latest stable release and now all tests are working again (working with Java 10.0.2, and 12.0.2). Can you now check if it's building in your system?

**Comment by mjw99** [comment]
I can now get this to compile on Ubuntu 18.04 with OpenJDK 11, however, I did need to change this in the pom.xml:

``
<javac.target>11</javac.target>
``

**Comment by DiegoEliasCosta** [comment]
This was a misstep of my patch. 
We should keep `java.target` at Java 8 as its largely supported.
